### ISSUE TITLE
Suggestion - Add name of more nopaste services

### ISSUE THREAD

**Issue by RCMainak** [wwphp-fb/wwphp-fb.github.io#22]
Yes, we can google it & the people sharing the code can google it as well but we all who does what lol. My proposal is to create a gist nicely formatted with names & links of nopaste services and add it to the TL;DR part of the CoC. Just a suggestion. Let me know what you think. I saw someone already has a good list of nopaste services in the fb group, can't remember who.

**Comment by peterkokot** [comment]
Sounds good to me... Currently there is gist mentioned and also linked, but more would definitely be useful to have for different tastes and cases. I'll add more to the list:

* http://sqlfiddle.com/
* http://codepen.io/
* https://jsfiddle.net/
* https://3v4l.org/
* https://eval.in/
* ...
and some more.

I wouldn't list all because of usability and simplicity.

Coming up.

**Comment by peterkokot** [comment]
I'm closing this issue in favor of https://github.com/wwphp-fb/conduct/pull/8

Feel free to discuss this further there. Thanks @RCMainak
